/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_lojaw_jni_KeyboardInputHandler */

#ifndef _Included_de_lojaw_jni_KeyboardInputHandler
#define _Included_de_lojaw_jni_KeyboardInputHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_lojaw_jni_KeyboardInputHandler
 * Method:    sendSignal
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_lojaw_jni_KeyboardInputHandler_sendSignal
  (JNIEnv *, jobject);

/*
 * Class:     de_lojaw_jni_KeyboardInputHandler
 * Method:    pressKey
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_de_lojaw_jni_KeyboardInputHandler_pressKey
  (JNIEnv *, jobject, jchar);

/*
 * Class:     de_lojaw_jni_KeyboardInputHandler
 * Method:    releaseKey
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_de_lojaw_jni_KeyboardInputHandler_releaseKey
  (JNIEnv *, jobject, jchar);

/*
 * Class:     de_lojaw_jni_KeyboardInputHandler
 * Method:    moveMouse
 * Signature: (IIZ)V
 */
JNIEXPORT void JNICALL Java_de_lojaw_jni_KeyboardInputHandler_moveMouse
  (JNIEnv *, jobject, jint, jint, jboolean);

/*
 * Class:     de_lojaw_jni_KeyboardInputHandler
 * Method:    getMousePosition
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_de_lojaw_jni_KeyboardInputHandler_getMousePosition
  (JNIEnv *, jobject);

/*
 * Class:     de_lojaw_jni_KeyboardInputHandler
 * Method:    mouseClick
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_lojaw_jni_KeyboardInputHandler_mouseClick
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
