/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_lojaw_SignalHandler */

#ifndef _Included_de_lojaw_SignalHandler
#define _Included_de_lojaw_SignalHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_lojaw_SignalHandler
 * Method:    sendSignal
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_lojaw_SignalHandler_sendSignal
  (JNIEnv *, jobject);

/*
 * Class:     de_lojaw_SignalHandler
 * Method:    pressKey
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_de_lojaw_SignalHandler_pressKey
  (JNIEnv *, jobject, jchar);

/*
 * Class:     de_lojaw_SignalHandler
 * Method:    releaseKey
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_de_lojaw_SignalHandler_releaseKey
  (JNIEnv *, jobject, jchar);

#ifdef __cplusplus
}
#endif
#endif
